### ISSUE TITLE
Font lock gives up after some point

### ISSUE THREAD

**Issue by matthewbauer** [matthewbauer/nix-mode#21]
This is a weird error, but sometimes font-lock seems to just give up and quit with the new fontification changes. Toggling (font-lock-mode) seems to fix it but it will show up again somewhere else after some edits are made.

<img width="574" alt="screen shot 2017-03-31 at 12 37 06 am" src="https://cloud.githubusercontent.com/assets/19036/24537785/846e48b2-15aa-11e7-8310-f0f7e1c1d438.png">

**Comment by ljli** [comment]
My guess is that there is an exception somewhere, maybe some out-of-bound stuff. The situation triggering the bug might only occur when smaller regions are refontified, which is why toggling `font-lock-mode` helps at first. Maybe there is an exception in *Messages*? If it is a bug it is likely that it occurs in `nix-syntax-propertize`. You could check with `describe-char` if the characters after the highlighting stops have the right syntax class and properties. If they were not processed by `nix-syntax-propertize` they would be all just in the word class, which would indicate that it crashed.

It did not happen to me, yet. If there is a way to reproduce this, I will look into it.

**Comment by matthewbauer** [comment]
I haven't been able to reproduce it recently either. It may have been caused by missing "case" which was just fixed. I'll close this if I haven't reproduced in a week or so.
