### ISSUE TITLE
`${` not correctly highlighted in double-quoted strings

### ISSUE THREAD

**Issue by taktoa** [matthewbauer/nix-mode#6]
A string of the form
```nix
"foo-${bar}"
```
gets blue highlighting for the initial `${` but otherwise is not correctly highlighted.

Note that that is a double-quoted string (`"foo"`) rather than a double-single-quoted string (`''foo''`), which has the correct behavior in nix-mode master.

Example screenshot:
![](https://i.imgur.com/0sprSlh.png)

**Comment by taktoa** [comment]
It's also worth noting that the following code is valid and evaluates to `"foo bar baz\nquux"`:
```nix
"foo ${
"bar"
} baz
quux"
```

Perhaps it would be worthwhile for Nix to have an optional dependency on [nlohmann/json](https://github.com/nlohmann/json) that adds a `--json` option to spit out the parsed AST of a given Nix expression, which editors could then use strategically.

**Comment by taktoa** [comment]
I have verified that this bug occurs upstream as well.

**Comment by matthewbauer** [comment]
:+1:

I can't quite figure out what's going on here.

Two other cases that are broken but should work are:

```
x = ''${asdf} '';
```

and

```
x = '' ${asdf}'';
```

**Comment by taktoa** [comment]
You may be interested in this issue I raised on Nix: https://github.com/NixOS/nix/issues/1102

**Comment by matthewbauer** [comment]
Eventually I want to write a proper nix parser in elisp similar to how js2-mode works. Most likely I'd try not to use nix-instantiate so we don't have to deal with the external process.

**Comment by matthewbauer** [comment]
Some notes on this issue:

* The antiquote syntax propertize function seems to not be able to "unquote" when it's inside of the prog-mode style strings. Perhaps it needs some more hints saying to treat `${` like `"`. Maybe we need to have a syntax property for old style `""`. The parser state seems to return "34" in these cases under slot 4 instead of the usual "t". See https://www.gnu.org/software/emacs/manual/html_node/elisp/Parser-State.html.
* The escaped antiquotes seem to be breaking `x = ''${asdf}''`. This rule should be ignored when we are outside of a multiline string.

**Comment by taktoa** [comment]
If we do end up getting a BNFC grammar for Nix, it might be more efficient to just write a new elisp backend for BNFC (if one doesn't already exist).

**Comment by matthewbauer** [comment]
This is all I've found: https://github.com/robstewart57/bnfc/commit/3bf49b354132a6eb47375c7e83eec30dcb2ddb54
